### ISSUE TITLE
Sync does not work when Opening/Ending is in the same folder (categorized as Specials)

### ISSUE THREAD

**Issue by katekyonni** [RickDB/PlexAniSync#47] opened 2021-02-01 23:43 UTC
First some infos:

Scanner: Absolute Series Scanner 
Metadata Provider: https://github.com/sachaw/anilist.bundle
I'm using the docker container.

After I updated my docker container to the new version the sync script would not run anymore.
I already chatted with @RickDB in discord and we probably found the problem, but need some input on how to fix it.

When there are OPs/EDs in the same folder as the series the .xml for them says `parentTitle="Specials"` but PlexAniSync expects a Season prefix like `parentTitle="Season 1"`

Is it the scanner that ist flagging the episodes as specials? https://github.com/ZeroQI/Absolute-Series-Scanner#specials

Would it be possible to just handle those episodes flagged as Specials as if it was Season 0?

I'll attach a log and the xml from an opening
[_plexanisync_logs (1).txt](https://github.com/RickDB/PlexAniSync/files/5907514/_plexanisync_logs.1.txt)
[112156.xml.txt](https://github.com/RickDB/PlexAniSync/files/5907517/112156.xml.txt)

**Comment by reconman** [comment] 2021-02-01 23:49
The behavior of detecting OPs and EDs as specials also happened to me, so it seems normal. But as soon as you have multiple seasons, the season association of episodes will be really messed up.

I would suggest moving the OPs and EDs to a `Specials` folder. I've never had sync problems so far with that approach.

**Comment by katekyonni** [comment] 2021-02-02 00:09
I just tried that but for me it would still detect them as specials :/

But isn't that the expected behavior? on the ASS Github it says "Specials go in "Specials" or "Season 0" folders." and it also says "You can use Anidb numbering for specials (OP1a, NCOP, etc...) or explicitely label them as follow (s00e101, etc...)."
So I think the files are handled the same if they are named NCOP or placed in the folder Specials.

I also have a different example:

Show: A-Channel:-+A-Channel (https://anilist.co/anime/10737/AChannel-AChannel/)
The Files are Named like this: A-Channel - SP01 [BDRip h264 1920x1080 FLAC][A8350932]    SP02, SP03 and so on

In this case every episode is detected as a Special and the sync does not run.

**Comment by katekyonni** [comment] 2021-02-03 00:39
Can you let me know if the following would theoretically be possible:

- completely ignore every episode that is detected as "Specials"
- except if every episode of a show is a special, then treat them as if it was Season 0 or 1

Sorry if this is a dumb idea 😅

**Comment by reconman** [comment] 2021-02-03 07:52
I thought that ignoring the specials was already part of the logic, I need some time to figure out what's going on.

**Comment by RickDB** [comment] 2021-02-03 08:31
We used to ignore Season 0 / specials before but it might be an unset season issue:

https://github.com/RickDB/PlexAniSync/blob/master/plexmodule.py#L176

If it lacks a season index but shows up in the episode metadata with a specials season number it will break.

**Comment by katekyonni** [comment] 2021-02-03 21:24
I've tried using an older version with this image: https://hub.docker.com/r/frosty5689/plexanisync
The image is using version 1.2.6 and I don't get any errors with that version.
I attached the log, maybe that can help somehow.
[_plexanisync-frosty_logs.txt](https://github.com/RickDB/PlexAniSync/files/5921602/_plexanisync-frosty_logs.txt)

**Comment by reconman** [comment] 2021-02-03 23:17
It's probably related to e13dde84282f78d596248bb71bfc52acd1a0cc00, one of my commits in November. I will need some new error logs from you with the newest commit. I can't reproduce it in my library with Hinamatsuri where I also have the OP and ED in it.

**Comment by katekyonni** [comment] 2021-02-04 15:38
Sure! The docker image isn't updatet yet though right?

**Comment by reconman** [comment] 2021-02-04 17:24
It is now, use the `latest` tag.

**Comment by katekyonni** [comment] 2021-02-04 17:41
Here's the new log:
[_plexanisync_logs 21-02-04.txt](https://github.com/RickDB/PlexAniSync/files/5927520/_plexanisync_logs.21-02-04.txt)

**Comment by reconman** [comment] 2021-02-04 22:14
Seems like your Plex metadata is messed up, the `parentKey` attribute is missing for the opening, which is used to find its season.

I've changed the code so it goes through the data like this `show -> season -> episode` instead of `show -> episode -> season`.

Can you try the latest image and tell me if it works?

**Comment by katekyonni** [comment] 2021-02-04 22:30
Nice it's working now!
Do you know if the `parentKey` is set by the Metadata Provider and we should notify the code owner of AniList.bundle?

[_plexanisync_logs 21-02-04 (1).txt](https://github.com/RickDB/PlexAniSync/files/5928896/_plexanisync_logs.21-02-04.1.txt)

**Comment by reconman** [comment] 2021-02-04 22:31
You mean Hama.bundle?

**Comment by katekyonni** [comment] 2021-02-04 22:35
No I'm using https://github.com/sachaw/anilist.bundle

**Comment by reconman** [comment] 2021-02-04 22:45
I would rather report it to the plexapi guy at https://github.com/pkkid/python-plexapi.

@katekyonni Can you please report the bug over there? I don't know your Plex version, so I can't fill out everything in the bug template.

The dev should be able to figure out what's happening based on your last log where the error was still there.

**Comment by reconman** [comment] 2021-02-04 22:46
Fixed by 00f632dc65560ee9c6b64c92e343b0ed2f4f0cf4

**Closed by reconman** 2021-02-04 22:46 UTC
